version: "3.9"

services:

  vault-server:
    container_name: vault-server
    image: vault:latest
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
    cap_add:
      - IPC_LOCK
    networks:
      vault-network:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server

  vault-client:
    container_name: vault-client
    build: ./vault
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    networks:
      vault-network:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-client

  spring-service:
    container_name: fertilizer-app
    depends_on:
      - vault-server
    build: .
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    image: fertilizer-app:latest
    ports:
      - "8080:8080"
    networks:
      vault-network:
        ipv4_address: 172.21.0.30
        aliases:
          - http-service

networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
